Add various design improvements
Voog/design-nuuk pull request #101
Opened 2022-05-13 09:14 UTC by PeeterPaal

Adds various design improvements:
* Use `object.og_image` method for OG image 
* Add titles & tooltips to various content areas
* Sync shopping cart icon between tabs

Closes #98 
Closes #99 
Closes #100

2022-05-16 10:47 UTC, tanelj approved these changes
Nice!

2022-05-16 11:37 UTC, tanelj requested changes
One small UX improvement request.

2022-05-16 11:37 UTC, tanelj commented on components/footer.tpl
> +            <div class="content-formatted mar_0-8">{% xcontent name=name title=footer_content_title title_tooltip=footer_content_title_tooltip %}</div>
Let's keep here only `title_tooltip`. Version with titles is too aggressive in Nuuk footer (multi column).
```suggestion
            <div class="content-formatted mar_0-8">{% xcontent name=name title_tooltip=footer_content_title_tooltip %}</div>
```

<img width="1362" alt="Screenshot 2022-05-16 at 14 34 47" src="https://user-images.githubusercontent.com/378755/168584236-31d9e0ca-de39-4f8c-a444-2a8b4a13299a.png">

2022-05-16 11:37 UTC, tanelj commented on components/footer.tpl
> +    {%- assign footer_content_title = "footer" | lce -%}
```suggestion
```

2022-05-16 13:14 UTC, tanelj approved these changes

2022-05-23 07:49 UTC, tanelj approved these changes
Nice!

2022-05-23 07:57 UTC, pxska approved these changes
Mõned stilistilised kommentaarid, mis tegelikult rohelist tuld ei peata – funktsionaalsus töötab kenasti!

Kuna meil hetkel veel Liquidi linterit kahjuks ei ole, siis võiksime natuke aega panna sellele, et ka Liquidi kood kena välja näeks, st mitte kirjutada üle 100 karakteri pikkuseid ridu (VSCode'is on ruler olemas, niiet saad selle järgi vaadata).

2022-05-23 07:57 UTC, pxska commented on components/header-fixed.tpl
> +      {% contentblock name="site_title" xpage="true"  publish_default_content="true" readonly=isReadOnly title=cross_site_title title_tooltip=cross_site_title_tooltip %}
Sellised megapikad read võiks breakida mitmele reale, kood näeb siis puhtam välja. Näiteks midagi sellist:

```suggestion
      {% contentblock 
         name="site_title"
         xpage="true" 
         publish_default_content="true"
         readonly=isReadOnly
         title=cross_site_title
         title_tooltip=cross_site_title_tooltip 
       %}
```

2022-05-23 07:57 UTC, pxska commented on components/header.tpl
> +      {% contentblock name="site_title" xpage="true" publish_default_content="true" readonly=isReadOnly title=cross_site_title title_tooltip=cross_site_title_tooltip %}
See ka mitmele reale:
```suggestion
      {% contentblock
         name="site_title"
         xpage="true"
         publish_default_content="true"
         readonly=isReadOnly
         title=cross_site_title
         title_tooltip=cross_site_title_tooltip
      %}
```

2022-05-23 07:57 UTC, pxska commented on components/post-box.tpl
> +      <div class="post_body content-formatted content-formatted--overflowed-images">{% content name="additional_body" bind="Article" title=bottom_content_title title_tooltip=bottom_content_title_tool
See ka mitmele reale:
```suggestion
      <div class="post_body content-formatted content-formatted--overflowed-images">
        {% content 
           name="additional_body"
           bind="Article"
           title=bottom_content_title
           title_tooltip=bottom_content_title_tooltip 
        %}
      </div>
```

2022-05-23 07:57 UTC, pxska commented on layouts/auto_generated_product.tpl
> +                {% content bind=product name="gallery" title=gallery_title title_tooltip=gallery_title_tooltip %}
See rida läheb ka juba pikaks:
```suggestion
                {% content
                   bind=product
                   name="gallery"
                   title=gallery_title
                   title_tooltip=gallery_title_tooltip 
                %}
```

2022-05-23 07:57 UTC, pxska commented on layouts/auto_generated_product.tpl
> +              {% content bind=product name="content" title=bottom_content_title title_tooltip=bottom_content_title_tooltip %}
```suggestion
              {% content
                 bind=product
                 name="content"
                 title=bottom_content_title
                 title_tooltip=bottom_content_title_tooltip
              %}
```

2022-05-23 07:57 UTC, pxska commented on layouts/blog___news.tpl
> +          <section class="content-body content-formatted mar_b-64">{% content title=content_title title_tooltip=content_title_tooltip %}</section>
```suggestion
          <section class="content-body content-formatted mar_b-64">
            {% content title=content_title title_tooltip=content_title_tooltip %}
          </section>
```

2022-05-23 07:57 UTC, pxska commented on layouts/product.tpl
> +                  {% contentblock title=content_title title_tooltip=content_title_tooltip %}{{ "write_product_description_here" | lc: editor_locale }}{% endcontentblock %}
```suggestion
                  {% contentblock
                     title=content_title
                     title_tooltip=content_title_tooltip
                  %}
                    {{ "write_product_description_here" | lc: editor_locale }}
                  {% endcontentblock %}
```

2022-05-23 07:57 UTC, pxska commented on layouts/product.tpl
> +            <section class="content-body content-formatted content-formatted--overflowed-images mar_b-32" data-search-indexing-allowed="true">{% content name="content" title=bottom_content_title titl
```suggestion
            <section
              class="content-body content-formatted content-formatted--overflowed-images mar_b-32" 
              data-search-indexing-allowed="true">
                {% content 
                   name="content"
                   title=bottom_content_title
                   title_tooltip=bottom_content_title_tooltip
                %}
            </section>
```

2022-05-23 07:57 UTC, pxska commented on layouts/product_list.tpl
> +            {% contentblock name="page_title" publish_default_content="true" title=page_title_content_title title_tooltip=page_title_content_title_tooltip %}
```suggestion
            {% contentblock
               name="page_title"
               publish_default_content="true"
               title=page_title_content_title
               title_tooltip=page_title_content_title_tooltip
            %}
```

2022-05-23 07:57 UTC, pxska commented on layouts/product_list.tpl
> +          {%- capture _bottom_content_html %}{% content name="bottom_content" title=bottom_content_title title_tooltip=bottom_content_title_tooltip %}{% endcapture -%}
```suggestion
          {%- capture _bottom_content_html %}
            {% content 
               name="bottom_content"
               title=bottom_content_title
               title_tooltip=bottom_content_title_tooltip
            %}  
          {% endcapture -%}
```

^ selle osas ma pole kindel, et see 100% õigesti töötab – võid üle kontrollida, kas see _bottom_content_html väärtustatakse õigesti, v-o on vaja kuskile mingeid strip'e (`{%-` `-%}`) panna

2022-05-23 07:57 UTC, pxska commented on sources/javascripts/concat/global/main.js
> +    var handleProductCountSync = function (e) {
Pisiasi, aga seda `e` argumenti sa siin vist ei kasuta? Kui nii, siis ei ole seda siia vaja.
```suggestion
    var handleProductCountSync = function () {
```

2022-05-23 07:57 UTC, pxska commented on sources/javascripts/concat/global/main.js
> +    })
Ja siis ei oleks siin samuti seda `e`-d vaja:
```suggestion
    $(document).on('voog:shoppingcart:contentschanged', function () {
      handleProductCountSync();
    })
```

2022-05-23 08:20 UTC, robertpih approved these changes

2022-05-26 10:30 UTC, merged