Remove reload on block & column count change
Voog/design-nuuk pull request #23
Opened 2021-03-11 10:10 UTC by siimha

Muutmise vaates renderdatakse kõik tulbad ja plokid, kuid peidetakse ära. Sisu ei kustutata, kui ridasid või tulpasid vähendatakse. Teistes vaadetes ei renderdata peidetud tulpasid ega plokke.

Close #22

2021-04-09 06:55 UTC, tanelj requested changes
Mõned teemad leidsin.

2021-04-09 06:55 UTC, tanelj commented on components/modular-blocks.tpl
> +    if ({{blockCount}} >= {{id}}) {
See koodijupp tuleks ümber kirjutada hetkel on siin mingi loogika vähemalt avalikus vaates vildakas. Nt kolme ploki korral genereeritakse seda koodi iga ploki jaoks, kus juures käima pannakse vaid viimane.
```
if (3 >= 1) {
...
if (3 >= 2) {
..
if (3 >= 3) {
```

2021-04-09 07:22 UTC, siimha commented on components/modular-blocks.tpl
> +{%- if editmode -%}
Sa mõtled siin `{%- if editmode and blockCount < 5 -%}`?

2021-04-09 07:24 UTC, tanelj commented on components/modular-blocks.tpl
> +{%- if editmode -%}
Jah :)

2021-04-09 07:55 UTC, siimha commented on components/modular-blocks.tpl
> +    if ({{blockCount}} >= {{id}}) {
Ma nüüd vaatan, et siin pole üldse `if` klauslit vaja. koodi peakski mitu olema, kuna igal plokil on oma stiilid.

2021-04-21 14:38 UTC, tanelj reviewed
Hertkel on (preview vaates) mingi `<div>` sulgemata kontrolli nt siin: https://validator.w3.org/#validate_by_input+with_options (ka masteris).

2021-04-21 14:38 UTC, tanelj commented on components/modular-blocks.tpl
>    <script>
Iga ploki jaoks renderdatakse siin JS plokk. Tundub üpris kulukas. Kas seda JS osa ei saa tõsta global.js funktsiooniks nii, et tema jaoks vajalikud algandmed tuleksid nt `block-container-ID` divi küljge pandavast data attribuudist ning funktsioon pannaks külge `block-container` blokkidele?

2021-04-26 10:52 UTC, siimha commented on components/modular-blocks.tpl
>    <script>
Ikka saab :)

2021-04-27 11:26 UTC, tanelj approved these changes

2021-04-28 14:20 UTC, robertpih approved these changes

2021-04-29 09:10 UTC, merged