Add shopping cart icon & animations according to design
Voog/design-nuuk pull request #31
Opened 2021-04-15 13:11 UTC by siimha

Close #28

2021-04-19 10:02 UTC, robertpih commented
Kas lehel olevas (onsite) ostukorvis peaks koguseid muutes popover nähtaval olema?
Lisaks on kaduma läinud `backdrop-filter` stiil. 

https://user-images.githubusercontent.com/27947082/115216947-a92ede80-a10d-11eb-87b1-2bbb985d845f.mov

2021-04-20 09:18 UTC, tanelj commented
> Kas lehel olevas (onsite) ostukorvis peaks koguseid muutes popover nähtaval olema?

Ei. "Veiw cart" badge peaks ilmuma vaid ostunupul toote ostukorvi lisamisel (`voog:shoppingcart:addproduct`).

Mõtteks: Küsimus disaini kohalt, mida arutada - pika tootenime korral peaks äkki tootenime ellipsiga lühendama teatud märgipikkusest alates.

2021-04-20 09:47 UTC, siimha commented
> Mõtteks: Küsimus disaini kohalt, mida arutada - pika tootenime korral peaks äkki tootenime ellipsiga lühendama teatud märgipikkusest alates.

Küsin stefanilt üle.

2021-04-21 13:54 UTC, tanelj requested changes

2021-04-21 14:13 UTC, tanelj commented on sources/components/custom-styles/template-cs-style-rules.scss
> +.edy-ecommerce-shopping-cart_btn:hover {
Kas siin on liiga hoogsalt saanud asendada?

EI näe, et `edy-ecommerce-shopping-cart_btn` kusagil kasutusel oleks. Küll aga genereerib ostukorvis skript `edy-ecommerce-shopping-cart-button` klassi.

2021-04-29 13:06 UTC, tanelj requested changes
Toimib küll kenasti ja ootuspäraselt, kuid küsitavus on ikooni kuvamises (peidetult, kuid ruumi võtvalt) siis, kui toodet pole korvis või pood pole aktiveeritud.

2021-04-29 15:11 UTC, tanelj requested changes
Ostukorvi osa töötab nüüd kenasti!

Kuid tekkis regressioon menüü "Side — opens on click" korral, kus saidi nimi oli enne (masteris) keskel, nüüd on vasakul (ja tühja sisu korral väike).

Enne 
![Screenshot 2021-04-29 at 18 00 46](https://user-images.githubusercontent.com/378755/116574233-334d2300-a916-11eb-8399-ff227e7f1908.png)

Nüüd
![Screenshot 2021-04-29 at 18 10 25](https://user-images.githubusercontent.com/378755/116574279-3f38e500-a916-11eb-8425-05ccb75453d2.png)

2021-04-30 09:18 UTC, tanelj approved these changes

2021-04-30 17:01 UTC, robertpih approved these changes

2021-05-03 05:48 UTC, merged