Use correct units for image size attribute
Voog/design-nuuk pull request #44
Opened 2021-06-02 08:58 UTC by siimha

Lisatud õiged ühikud pildi suuruste määramiseks.
Rohkem infot img täägi ja atribuutide kohta https://www.keycdn.com/blog/responsive-images.

Close #43

2021-06-02 09:46 UTC, siimha commented
Lisaks teha:
* [ ] lubada srcseti kõik suurused, et retina ekraani puhul oleks võimalik kasutada suuremat pilti.
* [ ] blogi listingus piirata väiksemate piltide suurust

2021-06-04 06:59 UTC, tanelj requested changes

2021-06-04 06:59 UTC, tanelj commented on components/lazy-image.tpl
> +  {%- assign sizes = "(min-width: " | append: _targetWidth | append: "px) " | append: _targetWidth | append: 'w' -%}
Siin on nüüd üks viga saanud parandatud teisega :) 

Mõlemad ühikud peavad olema px `(min-width: 700px) 700px` ehk:

```
{%- assign sizes = "(min-width: " | append: _targetWidth | append: "px) " | append: _targetWidth | append: 'px' -%}
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-sizes

2021-06-04 08:08 UTC, tanelj approved these changes

2021-06-04 09:02 UTC, merged