Add initial top menu dropdown functionality
Voog/design-nuuk pull request #50
Opened 2021-08-11 15:35 UTC by pxska

Lisatud on algne ülemise menüü _dropdown_i funktsionaalsus.

Closes #49.

2021-08-12 09:26 UTC, tanelj requested changes

2021-08-12 09:26 UTC, tanelj commented on sources/stylesheets/menus/_menus.scss
> +        background-image: url('/assets/chevron-down-black.svg');
Keskselt hostilt serveerituna on oluline, et assetite teed on suhtelised (`../`) mitte absoluudsed (`/`). Kuna `assets` ja `stylesheets` kasutad on samal tasemel siis peab olema `'../assets/chevron-down-black.svg'.

2021-08-12 09:26 UTC, tanelj commented on components/menu-main-iteration.tpl
> +            {% include "menu-dropdown-popover" %}
Praegu lisatakse `menu-dropdown-popover` ja `dd-arrow` klass ainult menuitemile, mille layout on Product või Product list. 

Peaks olema ka teistel lehtede.

Veel täpsemalt product lehe ja product listing lehe korral tohiks ilmselt menüüd/menüüs näidata alamelemente ainult siis, kui nad ei ole tootelehed või listingu lehed (v.a. siis, kui seadetes on toodete/listingute kuvamine lubatud).

Ehk siin ilmselt parim lahendus see, kui püüda komponendi sisu enne `{%- if item.layout_title == product_list_layout or item.layout_title == product_layout %}` kinni

```
{%- capture menu_dropdown -%}
          {% if item.visible_children.size > 0 %}
            {% include "menu-dropdown-popover" %}
          {% endif %}
{%- endcapture -%}
```

Ning renderdada siis kui `menu_dropdown != blank` (sh samal alusel `dd-arrow` klass). (nt nagu siin: https://github.com/Voog/design-berlin/blob/master/components/submenu.tpl)

2021-08-12 09:26 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +      {%- for child in item.visible_children -%}
See komponent peaks arvestama toote ja tootelistingu menüüs kuvamise lubamisega. Ning lahendada saaks capture'iga (nt siin: https://github.com/Voog/design-berlin/blob/master/components/submenu.tpl)

2021-08-12 09:31 UTC, pxska commented on components/menu-dropdown-popover.tpl
> +          {%- menulink child current-class="active" wrapper-class="menu-item lvl-2" untranslated-class="untranslated fci-editor-menuadd" -%}
Siinkohal teoreetiliselt ei oleks siis ka `current-class` väärtust vaja, sest ka see on by default "active"?

2021-08-12 09:34 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +          {%- menulink child current-class="active" wrapper-class="menu-item lvl-2" untranslated-class="untranslated fci-editor-menuadd" -%}
current-class default väärtus on `current`. Seega kui siin on vaja `active` siis on see vajalik.

2021-08-13 13:47 UTC, tanelj requested changes
Mõne kommentaarid + üks toimivuse teema:

* [ ] Kui elemente on rohkem ja nad lähevad "..." dropdownid, siis seal sees elementidel:
  * Edit vaates ei ole noolekest näha
  * Preview vaates on nooleke näha, kuid element on nihkes (vaata pilti)
  * Hoverdamine ei kuva alamlehti.

![Screenshot 2021-08-13 at 16 43 43](https://user-images.githubusercontent.com/378755/129366762-63698773-68fc-4904-ae31-ed983d6cdbc4.png)

2021-08-13 13:47 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +<div class="js-prevent-sideclick dropdown_menu-popover--wrap" data-sideclick="prevent">
Siin peaks olema pigem nii

```liquid
{% capture _dd_menuitems %}
...
{% endcapture %}

{% if _dd_menuitems != blank %}
  <div class="js-prevent-sideclick dropdown_menu-popover--wrap" data-sideclick="prevent">
  <nav data-url="{{ item.url }}" class="dropdown_menu-popover">
      <ul class="menu menu-vertical menu-public">
      {{ _dd_menuitems }}
      </ul>
    </nav>
  </div>
{% endif %}
```

2021-08-13 13:47 UTC, tanelj commented on components/menu-main-iteration.tpl
> +          {% include "menu-dropdown-popover" %}
Korrektne oleks renderdatav `item` komponendile ette anda. Komponent teeb muidu liiga tugeva eelduse, et selline muutuv muutuja nagu item on eelnevalt defineeritud:

```liquid
{% include "menu-dropdown-popover" item: item %}
```

2021-08-13 13:47 UTC, tanelj commented on components/menu-main-iteration.tpl
> +        {% if item.visible_children.size > 0 %}
See `item.visible_children.size > 0` võib olla hoopis `menu-dropdown-popover' komponendi sees.

2021-08-13 13:47 UTC, tanelj commented on components/menu-main-iteration.tpl
> +          {% if dd_menuitems != blank %}
Võimalusel peaks vältima selliste alamkomponendi poolt tehtud muutujate kasutamist (on ka erand juhte). Ehk siin võiks olla (kontrollime seda, mida renderdame):

```liquid
          {% if menu_dropdown != blank %}
```

2021-08-19 12:23 UTC, tanelj requested changes
* [x] Dropdown menüü elemendil on puudu `untranslated` stiil (ei ole eristuvad)

2021-08-19 16:46 UTC, pxska commented on components/menu-main-iteration.tpl
> +            data-arrow="active"
Minu loogika siin oli see, et selle itemi algne `data-arrow` state on itemit luues alati `active` ehk tõene, kuid pärast muudetakse vastavalt seadetele (kas product listi näidatakse, kus menüü on jmt) siis `inactive` staatusesse või jäetakse `active` staatusesse.

2021-08-19 16:50 UTC, pxska commented on components/menu-main-iteration.tpl
> +  {%- if item.layout_title == product_layout and isProductItemVisible -%}
Minu arust ei ole kõikide andmete korral – see if-else on siia lisatud selleks, et ta kontrolliks product ja product listi puhul (mida saab värvipoti ikoonist määrata) ka seda, kas see item on visible või mitte. Ehk kui on product või product_list mall ja kui vastav "is...Visible" on tõene, siis ta määrab `displayArrow` väärtuse. Kui ei ole tõene, siis väärtust ei määrata. Ja kui tegemist ei ole product ega product_list malliga, siis on `displayArrow` niikuinii väärtustatud, sest sellistes olukordades kuvatakse alati dropdowni.

2021-08-19 16:54 UTC, pxska commented on components/menu-main-iteration.tpl
> +  {%- if item.layout_title == product_layout and isProductItemVisible -%}
Aga positioning if-lause kohta oli märkus õige – see oli jäänud koodi üleliigse kontrollina sisse!

2021-08-23 06:46 UTC, tanelj commented on components/menu-main-iteration.tpl
> +  {%- if item.layout_title == product_layout and isProductItemVisible -%}
Millele viitan, on see, et seni kuni kõigi IF'i, IF ELSE ja ELSE klauslite tagastatav väärtus on sama, ei ole IF'il mingit semantikat :)

Ehk see:

```liquid
{%- if item.layout_title == product_layout and isProductItemVisible -%}
  {%- assign displayArrow = "dd-arrow" -%}
{%- elsif item.layout_title == product_list_layout and isProductListItemVisible -%}
  {%- assign displayArrow = "dd-arrow" -%}
{%- else -%}
  {%- assign displayArrow = "dd-arrow" -%}
{%- endif -%}
```

On täpselt sama, mis lihtsalt:

```liquid
  {%- assign displayArrow = "dd-arrow" -%}
```

2021-08-23 08:55 UTC, pxska commented on components/menu-main-iteration.tpl
> +  {%- if item.layout_title == product_layout and isProductItemVisible -%}
Ahaa, seda küll. Kas Liquid lubab `and` ja `or` operaatoreid niimoodi chainida, et selline lahendus töötaks?

```liquid
{% unless item.layout_title == product_layout and isProductItemVisible != true or item.layout_title == product_list_layout and isProductListItemVisible != true %}
  {% assign displayArrow = "dd-arrow" %}
{% endunless %}
```

2021-08-23 11:07 UTC, tanelj commented on components/menu-main-iteration.tpl
> +  {%- if item.layout_title == product_layout and isProductItemVisible -%}
Niimoodi chainida saab, kuid tulemus ei ole ootuspärane, sest tegelikult tahaksid sa kasutada sulgusid, kuid Liquid ei toeta (sulgudega) grupeerimist:

```
unless (item.layout_title == product_layout and isProductItemVisible != true) or (item.layout_title == product_list_layout and isProductListItemVisible != true) %
```

Tegelikult tahad sa siis pigem nii:

```liquid
{%- if isProductItemVisible == false and item.layout_title == product_layout -%}
  {%- assign displayArrow = "" -%}
{%- elsif isProductListItemVisible == false and item.layout_title == product_list_layout -%}
  {%- assign displayArrow = "" -%}
{%- else -%}
  {%- assign displayArrow = "dd-arrow" -%}
{%- endif -%}
```

Ehk tähis on siis ka `displayArrow` väärtuse "nullimine", kuid väärust olla tohi (ilma elsita itereerides jääks väärtuseks viimati kasutatud väärtus.

Lisaks on "odavam" komtrollida muutujat (`isProductItemVisible == false`) ja siis objekti (`item.layout_title == product_layout` ehk kui esimene kontrollitav on väär, siis ei hakata järgmist tingimust käivitama.

Lähemalt vaadates ei tundu see loogika (toote listi puhul `dd-arrow` mitte näitamine) loogiline, kuna (kus item on peamenüü element):
* ka tootelisti ja toote lehe all võib olla välja kuvatavaid lapsi (mitte toote/ tootelist tüüpi lehti)
* see loogika mõjutaks vaid muutmis vaadet (et listide kuvamise toggeldamine seadetes toimiks), previews nagunii `isProductItemVisible == false` korral itemit välja ei renderdata.
* Noole näitamine sõltub puhtalt sellest, kas `menu_dropdown != blank`

Lühidalt Tundub, et õige on järgmine:

Seda if'i pole vaja, kuna noole näitamine sõltub puhtalt sellest, kas `menu_dropdown != blank`.

Ehk kohad, kus on loogika:

```
{% if menu_dropdown != blank and item.visible_children.size > 0 %}{{ displayArrow }}{% endif %}
```

Peaks olema lihtsalt:

```
{% if menu_dropdown != blank%}dd-arrow{% endif %}
```

2021-08-23 11:16 UTC, tanelj requested changes

2021-08-23 11:16 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +{% if _dd_menuitems != blank and item.visible_children.size > 0 %}
Lisakontroll `item.visible_children.size > 0` ei ole vajalik, kuna ainult `item.visible_children.size > 0` korral saab `_dd_menuitems` üldse sisu olla (itereeritakse üle `item.visible_children`)

2021-08-23 11:16 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +        <{{tag}} class="menu-item-product menu-item" data-visible="{{ isProductItemVisible }}">
Praegu renderdatakse tooteleht alati menüüs ka preview ja public modes. Data visible on vajalik vaid muutmise vaates ilma reloadita disainis seadete rakendamiseks. Previews ei tohiks need elemendid HTML'i sattuda.


Ehk siin (ja all tootelisti juures) peaks olema:

```liquid
{% if editmode or isProductItemVisible == true %}
  <{{tag}} class="menu-item-product menu-item" data-visible="{{ isProductItemVisible }}">
    {%- menulink child current-class="active" wrapper-class="menu-item lvl-2" -%}
  </{{tag}}>
{% endif %}
```

Igaks juhuks küsin üle, et miks siin olenevalt nähtavusest erinev taga (div/li) üldse vajalik on?

2021-08-23 11:48 UTC, pxska commented on components/menu-dropdown-popover.tpl
> +        <{{tag}} class="menu-item-product menu-item" data-visible="{{ isProductItemVisible }}">
Jah, ei olnud tõesti div ja li tag'i eristamine vajalik! 👍🏻 Tegin seda vist sellepärast, et eeldasin, et kuna `menu-main-iteration` komponendis on seda ka kasutatud, siis et li elemendile ei saa `display: none` määrata, aga ikka saab. :D `data-visible` elemendid tegin kõik public vaatest peidetuks.

2021-08-24 12:12 UTC, tanelj requested changes
* [x] menuSubItemDisplayClass - nimi viitab, et muutuja sisuks on klassi nimi, tegelikult on boolean väärtus. Võiks ümber nimetada `isZXXX` (a la `isSubMenuItemVisible` vms)
* [x] siin reas https://github.com/Voog/design-nuuk/blob/e6e417927b8b43e6671725f21ed9213bdadc4820/components/menu-main-iteration.tpl#L108, on `isMenuItemVisible` väärtus renderdatud klassi sisse ja tekib olukord `class="menu-item-product-list false"`. Peab olema `"menu-item-product-list" data-visible="false"`. Selle tõttu nt kui olla I taseme "Product list" lehel ning "product list" tüüpi elementide kuvammine on keeletaud, siis kuvatakse Side menüü korral II taseme elemente hetkel välja.
* [x] sama olukord nagu eelmises punktis (https://github.com/Voog/design-nuuk/blob/e6e417927b8b43e6671725f21ed9213bdadc4820/components/menu-main-iteration.tpl#L151)
* [ ] Kui menüüelemendi data-visible on false siis HTMLis tohib teda välja näidata ainult muutmise vaates (liquids peab olema nt tingimus `editmode or isSubMenuItemVisible`). Vaatata `menu-main-iteration` komponent selle pilguga üle. Sh ei tohi avalikus vaates renderdada koodi II taseme menüüd, kui parent item on küll `selected?` kuid teda on keelatud menüüs näidata (nt tootelist). Ehk

See:
```liquid
    {{menu_main_lvl_1_item}}
      {%- if item.selected? -%}
```

Peaks olema pigem:
```liquid
    {{menu_main_lvl_1_item}}
      {%- if item.selected? -%}
        {%- if editmode or isMenuItemVisible -%}
```

2021-08-24 12:12 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +{% if editmode or menuPosTop == true %}
See kontroll peaks olema kogu komponendi sisu ümber, et menüü elementi ei hakataks asjata läbi protsessima. Jätaks selle isegi siit komponendist välja ja kontrolliks include'imisel

```liquid
{% if editmode or menuPosTop == true %}
  {%- if item.translated? -%}
    {% include "menu-dropdown-popover" item: item %}
  {%- endif -%}
{%- endif -%}
```

2021-08-25 14:28 UTC, tanelj requested changes
Toimib nüüd juba tegelikult täiesti õigesti, kuid veel viimased loogilised kommentaarid tulid.

2021-08-25 14:28 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +
Topelt tühi rida.

2021-08-25 14:28 UTC, tanelj commented on components/menu-dropdown-popover.tpl
> +        <li class="menu-item-product-list menu-item" {% if editmode or isProductListItemVisible == true %}data-visible="{{ isProductListItemVisible }}"{% endif %}>
Sama probleem, mis ees pooll. Palju koodi.

2021-08-25 14:28 UTC, tanelj commented on components/menu-main-iteration.tpl
> +          {%- menulink item current-class="active" wrapper-class="menu-item lvl-1" -%}
Siin on indent paigast läinud.

2021-08-25 14:28 UTC, tanelj commented on components/menu-main-iteration.tpl
> +                    {% if editmode or isSubMenuItemVisible %}data-visible="{{isSubMenuItemVisible}}"{% endif %}
Peaks olema ilmselt:

```liquid
{% if editmode %}data-visible="{{isSubMenuItemVisible}}"{% endif %}
```

2021-08-25 14:28 UTC, tanelj commented on components/menu-main-iteration.tpl
> +        <div class="add-submenu {% if item.layout_title == product_list_layout or item.layout_title == product_layout %}{{itemClass}}{%- endif -%}" {% if editmode or isMenuItemVisible == true %}data-
Siin peaks ilmselt olema:

```liquid
{% if editmode  %}data-visible="{{isMenuItemVisible}}"
```

2021-08-31 09:56 UTC, tanelj requested changes
Paistab, et leidsin ühe viimase kõrvalekalde:

* [ ] Kui top menüül on palju elemente siis eraldi dropdown menüü hover värv on valeks läinud (varem muutus ainult tausta värv, kuid teksti värv jäi samaks):

![Screenshot 2021-08-31 at 12 47 46](https://user-images.githubusercontent.com/378755/131481506-15816ff1-8f85-433b-adb7-e4989dbf0b81.png)

2021-08-31 10:54 UTC, tanelj approved these changes

2021-08-31 11:49 UTC, robertpih approved these changes
Kena!

2021-08-31 11:56 UTC, merged