Add functionality for changing blog layout
Voog/design-nuuk pull request #56
Opened 2021-08-27 12:42 UTC by PeeterPaal

Add the option to change between different blog layouts.

Closes #53

2021-09-10 10:35 UTC, robertpih requested changes
Töötab kenasti, mõned väikesed asjad jäid silma.

2021-09-10 10:35 UTC, robertpih commented on components/template-settings-json.tpl
> +
Üleliigne reavahetus

2021-09-10 10:35 UTC, robertpih commented on layouts/blog___news.tpl
> +              <div class="blog_listing-item {% if blog_layout_setting == "list" %}list {% elsif blog_layout_setting == "highlight_with_popout" %}highlight-with-popout {%endif%}">
Üleliigne whitespace

2021-09-13 17:13 UTC, robertpih commented
Kena, loogika toimib.

2021-09-16 06:59 UTC, robertpih approved these changes

2021-09-16 11:47 UTC, tanelj reviewed
Kena ja toimib!

Peidame siis praegu kasutajaliidese kaudu blogi layouti seadistamise ära (jääb ainult võimalus üle API seadistada:

`PUT /admin/api/pages/12113/data/nuuk_blog_settings.json`

```json
{"value":{"blog_layout":"highlight_with_popout"}}
```

Peamise koodi jätaks malli alles. Kommenteeriks välja nt nii:

```
{%- comment -%}{% include 'settings-blog-page-layout' %}{%- endcomment -%}
```

lisaks vajadusel muudatused mujal koodis, kui vaja.

Master haru tuleks ka sisse tõmmata tõmmata ja assetid läbi protsessida.

2021-09-16 13:58 UTC, tanelj approved these changes

2021-09-16 13:58 UTC, merged