Add modular blocks to front page layout
Voog/design-nuuk pull request #64
Opened 2021-09-21 11:09 UTC by PeeterPaal

Lisatud modulaarsete plokkide tugi front page mallile.

Closes #59

2021-09-24 10:02 UTC, pxska requested changes

2021-09-24 10:02 UTC, pxska commented on layouts/front_page.tpl
> +            {%endcomment%}
Kommentaare ei ole vaja lõpus sisse jätta.

2021-09-24 10:02 UTC, pxska commented on layouts/front_page.tpl
> +  {%comment%}{% include 'settings-popover', _frontPage: true %}{%endcomment%}
Kommentaarid võib ära eemaldada (kui seda include'i ei kasutata, siis koos sellega).

2021-09-24 12:44 UTC, tanelj commented on components/modular-blocks.tpl
> +    {%- if _frontPage -%}
Siin ja all saaks lihtsamalt:
Ees pool:
```
{%- if _frontPage -%}
  {%- assign _columnBaseKey = template_settings.page.block_columns_settings_front_page.key -%}
{%- else -%}
  {%- assign _columnBaseKey = template_settings.page.block_columns_settings.key -%}
{%- endif -%}
```

Ning siin ja all kasutamine:
```
{%- assign blockColumnsSettingsKey = _columnBaseKey | append: id -%}
```

2021-09-27 08:47 UTC, pxska approved these changes
Minul töötab hästi!

2021-09-27 10:19 UTC, tanelj commented on components/settings-popover.tpl
> +        _blockSettings: _blockSettings, _defaultBlockObj: _defaultBlockObj
Siin ja eelmises plokis oleks korrektne ette anda ka siia kõrgemalt poolt include'il ette antud `_columnBaseKey` (ehk siin juurde `, _columnBaseKey: _columnBaseKey`).

Sama ka commonPage tüübi korral.

Hetkel see see toimib, sest kord defineeritud muutuja on defineeritud "ees pool". Samas see oletus muutub nõrgaks kui tekib vajadus teha `{% include 'settings-modular-content' %}`  mujal.

Seega võiks selle koha ära korrigeerida.

2021-09-27 10:21 UTC, robertpih commented
Minul töötab ka kenasti. Üks väikene asi, mis võibolla vääriks ilmselt tähelepanu: 
Praegu on Nuukil esilehe sisualablokil `margin-top: 32px`, mida nüüd aga pole ja õhku elementide vahel napib:
![Screenshot 2021-09-27 at 13 17 53](https://user-images.githubusercontent.com/27947082/134890436-1cad80d1-c10d-4077-a419-6517f8b3fb48.png)
vs: 
![Screenshot 2021-09-27 at 13 21 07](https://user-images.githubusercontent.com/27947082/134890891-a1cc5a53-1b3f-47fe-8112-050d6438ce5d.png)

2021-09-27 10:35 UTC, tanelj requested changes
Toimib kenasti, vaid üks visuaalne regressioon.

2021-09-27 10:35 UTC, tanelj commented on layouts/front_page.tpl
> -            <section class="content-body content-formatted{% if front_main_has_content or editmode %} mar_t-32{% endif %}" data-search-indexing-allowed="true">{% content %}</section>
Kadus ära slogan ja alumiste plokkide vaheline 32 px margin.
Siin oleks ehk lahendus panna top 32 asemelt slogan alale buttom 32?

```
"content-slogan content-formatted js-content-optional{% if front_main_has_content or editmode %} mar_b-32{% endif %}"
```

2021-09-27 10:53 UTC, robertpih approved these changes

2021-09-27 10:57 UTC, tanelj approved these changes

2021-09-27 12:05 UTC, merged