Load all products in related products list
Voog/design-nuuk pull request #69
Opened 2021-10-28 06:17 UTC by pxska

Varasemalt laeti seotud toodete nimekirjas vaid esimesed 250 toodet. Antud PR käib läbi kõik leheküljed toodete nimekirjas.

Closes #68

2021-11-01 07:08 UTC, tanelj commented on components/settings-product-page.tpl
> +            promises.push(getProductsPage(i));
Jah, paralleelsus on tore asi, kuid mitte API's, kus meelega on päringud pagineeritud ja max itemite arv määratud  (ainult rate limit on veel puudu). Parim põhimõte oleks laadida alati minimaalselt. Samas päringute arv vs päringu kiiruse vahel on tavaliselt vaja leida balanss (mida suurem tagastatav "ports", seda kauem üldiselt läheb (sh esimese renderduse jaoks), samas palju väikeseid päringuid tehes võib ühenduste tekitamiseks rohkem aega kuluda).

 Siin kas
a) Lazy load, mis laeb nt esimese portsu tooteid ning listi ülejäänud elemendid laetakse siis, kui kasutaja alla poole kerib
b)  Lookup, mis laeb nt esimese portsu tooteid ning listi ülejäänud elemendid laetakse siis, kui sisestab märksõnu (sel juhul iga klahvivajutus ei tohiks saata päringut, vaid klahvivajutused tuleks kokku koguda)
c) Laetakse kõik itemid jadamisi.

Kuna siin kuvatakse sama selecti tulles vaates kolm korda ja meil veel ei ole mallis lookup komponenti, siis hetkel kiireim viis tundub c).

2021-11-01 10:35 UTC, tanelj requested changes
Toimib kenasti, kuid panin pagineerimise arvu ja sortimise kohta veel kommentaari.

2021-11-01 10:35 UTC, tanelj commented on javascripts/editmode.js
> +            '&per_page=25' +
Tõstame siin limiidi maksimaalse 250 peale.

2021-11-01 10:35 UTC, tanelj commented on javascripts/editmode.js
> +            if (page < numberOfPages) {
Kuna BuyButtons API ei toeta üle toote väljade (v.a. ID) filtreerimist ja sortimist, siis tuleks `productsPageList` array mõistlikuks kasutamiseks sorteerida `title` genereeritud title väärtuse järgi.

2021-11-01 14:01 UTC, tambeta requested changes
Küsimus: kas failid `sources/javascripts/concat` kataloogis on puhtalt programselt genereeritud (s.t. Grunt lükkab need kokku?). Hetkel näen sama koodi diffis topelt. Kui jah, siis võiks need [nt binaarseks märkida](https://git-scm.com/book/en/v2/Customizing-Git-Git-Attributes), et diffi ei risustaks.

2021-11-02 07:14 UTC, pxska commented on javascripts/editmode.js
> +            if (numberOfPages === undefined) {
Üritasin parandada veaolukorda, mis osutus hoopis bugiks. Nüüd korras. :-)

2021-11-02 07:26 UTC, pxska commented
> Küsimus: kas failid sources/javascripts/concat kataloogis on puhtalt programselt genereeritud (s.t. Grunt lükkab need kokku?). Hetkel näen sama koodi diffis topelt. Kui jah, siis võiks need nt binaarseks märkida, et diffi ei risustaks.

Grunti kokku lükatud failid on `javascripts/` kataloogis – seal lükatakse `/concat` kataloogist failid ühte kohta kokku ja minifitseeritakse. Kas sellisel juhul oleks kõige õigem märkida `javascripts/` kataloogis olevad (mitte-minifitseeritud) failid binaarseks?

2021-11-02 08:12 UTC, tambeta commented
>Kas sellisel juhul oleks kõige õigem märkida `javascripts/` kataloogis olevad (mitte-minifitseeritud) failid binaarseks?

Jah, pigem küll. Kui neid käsitsi ei muudeta, võib neid mustade kastidena käsitleda ja diff on puhas (lisaks annab mallikaugele arendajale (nagu mina) märku, et neid ei peaks käppima). Tüüpiliselt kokku ehitatud tulemeid repos muidugi ei hoitagi, aga kuna see on mugav, siis ei hakkaks siin praegu muudatusi tegema.

2021-11-02 08:16 UTC, pxska commented on javascripts/editmode.js
> +    window.addEventListener('DOMContentLoaded', function() {
Mooduleid ma hetkel tegema ei hakanud – panin aga endale kirja ning võiks olla tulevikus üks Nuuki korrastamise/refaktoorimise teemasid, sest samuti on `editmode.js` failis kasutusel ka näiteks `initSettingsEditorBtn`, mis paistab selle loogika järgi samuti hea kandidaat modulariseerimiseks.

2021-11-02 13:18 UTC, tambeta requested changes

2021-11-02 13:18 UTC, tambeta commented on .gitattributes
> +javascripts/global.js binary
Githubil tundub suva olevat ja näitab ikka diffi. Git teeb õigesti ja ei näita.

2021-11-02 13:18 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +          '&per_page=1' +
See on kogemata sisse jäänud?

2021-11-02 13:18 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +          if (page <= numberOfPages) {
See ei tundu õige olevat. Olgu kokku n lehekülge, siis kui `page` == n, üritatakse järgmisena tõmmata lehekülge n + 1.

2021-11-02 13:18 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +        async: false,
Ma kahtlustan, et see [ei tee midagi](https://api.jquery.com/jQuery.ajax/) ja tuleks kustutada.

>As of jQuery 1.8, the use of `async: false` with jqXHR (`$.Deferred`) is deprecated; you must use the success/error/complete callback options instead of the corresponding methods of the jqXHR object /---/

Sünkroonne käitumine oleks siin päris halb idee nagunii.

2021-11-02 13:18 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +      }).done(sortProductsPageList());
Vähemalt koodi vaadates on mul tunne, et nüüd kutsutakse `sortProductsPageList` välja pärast iga päringut (sest kasutad `getAllProducts` rekursiivselt). Vii see parem tagasi sinna, kus seda varem tegid.

Kenam lahendus oleks eraldada funktsioonid `getAllProducts` ja `getProductsPage`; tekitada (ja tagastada) viimases `Promise`, mis laheneb alles viimase lehekülje laadimisel ning seepeale ka list sortida. Kuid see ei ole praegu tingimata vajalik.

2021-11-03 08:05 UTC, pxska commented on .gitattributes
> +javascripts/global.js binary
Uurisin järele ja paistab tõesti, et GitHubi üldse ei huvitagi failide binaarseks märkimine, aga lihtsalt `git diff` tehes on ta tore abivahend.

2021-11-03 09:36 UTC, tambeta commented on .gitattributes
> +javascripts/global.js binary
Ühel hetkel tuleks ka mitte-deprecated standardmallid (mis on hägune hulk, aga minu nägemuses ainult Nuuk hetkel) siiski tänapäeva tuua. Ehk kokku ehitamine webpacki peale tuua, lisada linterite konf, võib-olla CI/CD (st constructionis võiks automaatselt viimane seis olla, aga v-o juba ongi nii) ja dockeri tugi tekitada. Ning selle käigus kokku ehitatud assetid repost ära koristada. Valmis ehitatud asju tuleks levitada reliisipakkidena.

2021-11-03 14:00 UTC, tambeta requested changes
Hetkel on suur probleem see, et kood ei arvesta asünkroonsusega. Need kommentaarid on allpool kirjas.

Selleks, et kood ka vähem hapraks saada, panen ette ka refaktoorimise (kogu jutt käib `initProductPageSettings` funktsiooni, sisuliselt mooduli, kontekstis):

* kaota ära globaalne (s.o. `initProductPageSettings` ülemises skoobis) `productsPageList` muutuja.
* kaota ära `sortProductsPageList` ja `parseResults`  funktsioonid.
* tee nii, et `getProductsPage` tagastaks (s.t laheneks) andmestruktuuri `{nPages, products}` ehk lehekülgede koguarvu ja toodete andmestruktuuri (otse see mis API-st tuleb)
* tee nii, et `getAllProducts` tagastaks toodete andmestruktuuri
* kui `getAllProducts` tagastatud Promise laheneb, siis tulemuseks on kogu toodete toores andmestuktuur. Anna see ette funktsioonile a la `getProductsPageList(products)`, mis katab ära vanad `parseResults` ja `sortProductsPageList` ülesanded ja tagastab lõpliku struktuuri

Mida see refaktoorimine saavutab?

* kaob ära "globaalne" (mooduli / ülemfunktsiooni skoobis) muutuja, mida siis kuskil siin ja seal mudimas käid
* API kallal käivate funktsioonide ülesanded muutuvad selgemaks ja kaovad kõrvalefektid
* kokkuvõttes on kood selgem, vähem aldis bugidele ja tulevasele arendajale väiksema kognitiivse koormusega

2021-11-03 14:00 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +      return numberOfPages;
Ma eeldan, et tahad siin tagastada lehekülgede arvu, mis serverist tuleb, mitte `undefined`. Selleks pead sa ikkagi tagastama `Promise` objekti, mille tagastab `$.ajax` ning selle hiljem lahendama, tagastades õige väärtuse `success` callback'is — asjad toimuvad asünkroonselt.

Reegel on see, et asünkroonne funktsioon tagastab alati `Promise`, ehk veksli väärtustamiseks tulevikus. `async` / `await` tänapäevases ES-is teeb selle palju mugavamaks.

2021-11-03 14:00 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +      var numberOfPages = getProductsPage(1, pageLanguageId)
Ning siin pead ootama, et tagastatud `Promise` laheneks ja siis edasi toimetama.

2021-11-03 14:00 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +            getProductsPage(i, pageLanguageId);
Siin toimuvad asjad nüüd paralleelselt, mitte jadamisi. Sa tulistad kõik 2..n päringut korraga välja.

2021-11-03 14:00 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +              sortProductsPageList();
Siin lähed listi sorteerima, enne kui viimane päring naaseb.

2021-11-08 14:29 UTC, tambeta requested changes
Päris kena, aga mõned kohad on veel veidi mudased.

2021-11-08 14:29 UTC, tambeta commented on sources/javascripts/concat/editmode/editmode.js
> +          resolve(getProductsPageList(productsPageList));
Siin on ka liiga keeruline. Kogu see funktsioon peaks tagastama toorstruktuuri API-st ja olema:

```js
var getAllProducts = function (pageLanguageId) {
  return getProductsFromPage(1, pageLanguageId);
};
```

2021-11-08 15:04 UTC, pxska commented on sources/javascripts/concat/editmode/editmode.js
> +        });
Jep, propageerub tõesti edasi ja ei ole vajalik.

2021-11-08 16:49 UTC, tambeta approved these changes
Kaunis. Kui nüüd päriselt töötab ka, siis :+1:

2021-11-10 15:24 UTC, tanelj approved these changes

2021-11-11 06:51 UTC, merged