Add more features for creating additional Nuuk-based layouts
Voog/design-nuuk pull request #88
Opened 2022-01-27 09:16 UTC by PeeterPaal

Add additional features for creating different Nuuk-based layouts

2022-01-31 13:24 UTC, tanelj requested changes
Some initial feedback mostly about menus.

* [ ] Let's prefer hosted Google Fonts over self hosted fonts.
* [ ] Mobile menu is not working for `"positioning": "is_top",`
* [ ] Submenu element are black for `"positioning": "is_top",`
<img width="1100" alt="Screenshot 2022-01-31 at 14 58 36" src="https://user-images.githubusercontent.com/378755/151798699-b0874a01-6862-4423-a574-a3318478cc3a.png">
* [ ] Menu dropdown arrows are not visible for dark menu bg.
<img width="629" alt="Screenshot 2022-01-31 at 15 08 29" src="https://user-images.githubusercontent.com/378755/151799079-3bf061b6-fcce-451f-b6d3-56cc9fb88292.png">
* [ ] Burger menu icon is not visible for side menu when the menu bg is set to dark.
<img width="136" alt="Screenshot 2022-01-31 at 15 09 43" src="https://user-images.githubusercontent.com/378755/151799338-938c0347-d8de-4489-9316-eabf5502d504.png">
* [ ] `active_element_indicator` setting should be selectable only for side menus.
* [ ] Maybe `show_articles_as_list` naming to `older_articles_as_list` is more accurate. Also it seem it's not good UX automatically hide all old articles. Maybe at least 1 (or X??) articles must be remain to "normal" mode.

2022-03-10 15:16 UTC, tanelj requested changes
Some first technical feedback.

2022-03-10 15:16 UTC, tanelj commented on components/header.tpl
> +{%- endif -%}
Better pattern (works also in case of `menuSettings.indicator == ""`)
```suggestion
{%- assign indicatorStyle = menuSettings.indicator | default: template_settings.site.menu_settings.value.indicator -%}
```

2022-03-10 15:16 UTC, tanelj commented on components/menu-main-iteration.tpl
> +{%- endif -%}
Better:
```suggestion
{%- assign maxMenuElements = menuSettings.max_elements | default: template_settings.site.menu_settings.value.max_elements -%}
```

2022-03-10 15:16 UTC, tanelj commented on components/post-box.tpl
> +        <div class="post_excerpt content-formatted content-formatted--overflowed-images mar_t-48 mar_b-64" {{ edy_intro_edit_text }}>{% editable article.excerpt %}</div>
`edy_intro_*`is now deprecated and should be removed.

2022-03-10 15:16 UTC, tanelj commented on components/settings-blog-page-layout.tpl
> +      valuesObj.no_of_articles_shown = 5;
It's better when the default value is not hardcoded

```suggestion
      valuesObj.no_of_articles_shown = {{ template_settings.page.blog_settings.value.no_of_articles_shown }};
```

2022-03-10 15:16 UTC, tanelj commented on components/settings-menu.tpl
> +        valuesObj.indicator = 'square';
Use template default value as souce if possible:
https://github.com/Voog/design-nuuk/blob/37c8707835300a9ac68c14eb8faffe24a800a585/components/template-settings-json.tpl#L18

2022-03-10 15:16 UTC, tanelj commented on sources/stylesheets/menus/_menus.scss
> +        //top: calc((var(--header-mainmenu-font-size) * var(--header-mainmenu-line-height)));
Comment.

2022-06-22 11:26 UTC, tanelj requested changes
Some comments

* [ ] Menu is not opened when kind is `is_side_absolute` (FF)

![Screenshot 2022-06-22 at 13 49 37](https://user-images.githubusercontent.com/378755/175017955-d0417f56-a3d2-447f-a13c-5a6e8d98eefd.png)

2022-07-11 13:50 UTC, pxska requested changes
Some comments & a question (feel free to argue with them all):
- When setting the front page header content area to be on the bottom left / bottom right, the area still moves to the center in mobile view – is this the expected behaviour?

2022-07-11 13:50 UTC, pxska commented on components/footer.tpl
> +      {%- endif -%}
Am I correct here that the default values are: `block_count`: 2 and `col_count`: 4? If so, then that should always be in the case in editmode (I am always shown 2 blocks and 4 columns)? If that should be the case, these clauses don't work for me: if I set both the `block_count` and `col_count` to 1, I am shown just one block in editmode.

EDIT: I am guessing it's because of the {% if %} sentences in [row 47](https://github.com/Voog/design-nuuk/pull/88/files#diff-04bae0adb6926ccf090b1f5619a84f2d7ca20bf8215e368766cbfc239ecd42adR47) and [row 65](https://github.com/Voog/design-nuuk/pull/88/files#diff-04bae0adb6926ccf090b1f5619a84f2d7ca20bf8215e368766cbfc239ecd42adR65).

2022-07-11 13:50 UTC, pxska commented on components/footer.tpl
> +      {%- if editmode and block_count < defaultFooterSettings.block_count -%}
Since we have `rows` and `columns`, I think that a better name for `block_count` would be `row_count`.

2022-07-11 13:50 UTC, pxska commented on components/footer.tpl
> +      {%- endif -%}
Maybe you can shorten these blocks by using `default` like you did [here](https://github.com/Voog/design-nuuk/pull/88/files#diff-4aef006608b6a167536b0ffac282c3e41cc684fe4a0b1c6cdc4c0e93fd3dd300R10)?

2022-07-11 13:50 UTC, pxska commented on components/menu-main-iteration.tpl
> +      {% endif %}
This can be shortened (might have to test it :D):
```suggestion
      {%- assign showInTopMenu = maxMenuElements > menuItemCount -%}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +          <time class="post_date {% if show_article_date == false %} hide-post-date{% endif %}{% if show_article_author == false or show_article_date == false %} mar_r-8{% endif %}{% if article_data_
Extra space here:
```suggestion
          <time class="post_date{% if show_article_date == false %} hide-post-date{% endif %}{% if show_article_author == false or show_article_date == false %} mar_r-8{% endif %}{% if article_data_show_date_defined != true %} site-data{% endif %}"
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +      {% if _isArticle == true and editmode == true %}
```suggestion
      {% if _isArticle and editmode %}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +          <div {% unless article.published? or _isArticle == true %}class="post_unpublished"{%- endunless -%}>
Move the space here & shorten:
```suggestion
          <div{% unless article.published? or _isArticle %} class="post_unpublished"{%- endunless -%}>
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +            {% include 'content-item', _imageData: article.data[itemImageKey], _entityData: article, _itemType: 'article', _id: article.id, _staticItem: isPostImageStatic, _targetWidth: _targetWidth
This should be on multiple lines for readability (are the commas necessary here?):
```suggestion
            {% include 'content-item',
               _imageData: article.data[itemImageKey],
               _entityData: article,
               _itemType: 'article',
               _id: article.id,
               _staticItem: isPostImageStatic,
               _targetWidth: _targetWidth 
            %}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +  {% if _showArticlesAsList == false or _isArticle == true %}
This can be shortened:

```suggestion
  {% if _showArticlesAsList == false or _isArticle %}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +    <header class="post_header{% if _isArticle == true %} post_header-stretch{% endif %}">
```suggestion
    <header class="post_header{% if _isArticle %} post_header-stretch{% endif %}">
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +        <div class="p-rel{% if _hideImage == true %} d-none{% endif %}">
```suggestion
        <div class="p-rel{% if _hideImage %} d-none{% endif %}">
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +          {%- unless article.published? or _isArticle == true -%}
```suggestion
          {%- unless article.published? or _isArticle -%}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +          {%- unless _isArticle == true -%}
```suggestion
          {%- unless _isArticle -%}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +      {% unless _isArticle == true %}
```suggestion
      {% unless _isArticle %}
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +    <div class="post_content{% if _isArticle == true %} post_narrow{% endif %}">
```suggestion
    <div class="post_content{% if _isArticle %} post_narrow{% endif %}">
```

2022-07-11 13:50 UTC, pxska commented on components/post-box.tpl
> +  {% endif %}
This could be written as an `elsif`:
```liquid
{% elsif _isArticle %}
  {{ post_details_list_view }}
{% endif %}
```

2022-07-11 13:50 UTC, pxska commented on components/settings-article-page.tpl
> +      hide_article_image_in_list: {%- if articleSettingsData.hide_article_image_in_list == true -%}true{%- else -%}false{%- endif -%},
Could these be shortened like this?
```suggestion
      hide_article_image_in_list: articleSettingsData.hide_article_image_in_list,
      ...
```

2022-07-11 13:50 UTC, pxska commented on components/settings-blog-page-layout.tpl
> +            "min": 3,
Maybe just a personal preference, but I would set the minimum here as 1.

2022-07-11 13:50 UTC, pxska commented on components/settings-menu.tpl
> +              $('.menu-elements-opt').addClass('d-none');
Maybe a personal preference here as well, but I would divide `removeClass`, `addClass` etc functions into separate groups, like this:
```suggestion
              $('.js-menu-popover, .js-menu-popover').addClass('d-none');
              $('.header_fixed_picker-btn').addClass('d-none');
              $('.menu-elements-opt').addClass('d-none');
              
              $('.dd-arrow').data('arrow', 'inactive');
              
              $('li.dd-arrow, div.dd-arrow').removeClass('dd-arrow');
              $('.menu-indicator-opt').removeClass('d-none');
```
...etc. But decide for yourself. :-)

2022-07-11 13:50 UTC, pxska commented on components/settings-blog-page-layout.tpl
> +          } else if (data.blog_layout == "list_cols_2") {
You have used strict equality operators below (`===`), but non-strict ones here (`==`) – strict operators are preferred and where applicable, should always be used.

2022-07-11 13:50 UTC, pxska commented on components/template-variables.tpl
> +      {
Just a random idea: if this is given to customers in the long run, maybe we should have "new" indicators in the design editor to show what's new?

2022-07-11 13:50 UTC, pxska commented on javascripts/global.js
> +          $('.semimodal_bottom .menu .menu-item.lvl-1').clone().appendTo('.menu_popover-list').addClass('editmode-list-element');
Does this class need to be removed once `editmode()` is `false`?

2022-07-11 13:50 UTC, pxska commented on layouts/blog___news.tpl
> +              {%- endif -%}
These can be shortened as well I think (?):
```suggestion     
              {%- assign hideImage = article.data.article_settings.hide_article_image_in_list -%}
              
              {%- assign showBorder = article.data.article_settings.show_border_around_article -%}

              {%- assign articleCount = blog_settings.no_of_unarchived_articles | default: default_blog_settings.no_of_unarchived_articles -%}
              
              {%- assign overLimit = forloop.index > articleCount -%}
```

2022-07-11 13:50 UTC, pxska commented on layouts/blog___news.tpl
> +              {% if show_older_articles_as_list == true %}
```suggestion
              {% if show_older_articles_as_list %}
```

2022-07-11 13:50 UTC, pxska commented on layouts/blog___news.tpl
> +                    {{ article_element_list }}
I'm guessing this should be like this (?):
```suggestion
                  <div class="w-100p mar_t-32 blog_listing-item-list">
                    {{ article_element_list }}
                  </div>
```

2022-07-11 13:50 UTC, pxska commented on layouts/front_page.tpl
> +        <div class="swiper-content content-formatted swiper-content-{{ swiperSettingsData.content_position | default: default_swiper_position }}" data-search-indexing-allowed="true">
This row can be shortened a bit:
```suggestion
        <div 
           class="swiper-content content-formatted swiper-content-{{ swiperSettingsData.content_position | default: default_swiper_position }}"
           data-search-indexing-allowed="true"
        >
```

2022-07-11 13:50 UTC, pxska commented on layouts/front_page.tpl
> +                    <div class="swiper-content content-formatted swiper-content-{{ swiperSettingsData.content_position | default: default_swiper_position }}" data-swiper-parallax="-100%" data-search-
```suggestion
                    <div 
                       class="swiper-content content-formatted swiper-content-{{ swiperSettingsData.content_position | default: default_swiper_position }}"
                       data-swiper-parallax="-100%"
                       data-search-indexing-allowed="true"
                    >
```

2022-07-13 06:18 UTC, PeeterPaal commented on components/footer.tpl
> +      {%- endif -%}
Here I used the same logic as in modular blocks – only these blocks are displayed in editmode that are also shown in public mode to avoid confusion. This could perhaps be further discussed.

2022-07-13 09:57 UTC, PeeterPaal commented on components/settings-article-page.tpl
> +      hide_article_image_in_list: {%- if articleSettingsData.hide_article_image_in_list == true -%}true{%- else -%}false{%- endif -%},
This seems to be necessary to also account for the default value, otherwise `null` will be saved to article data if no value has been set. The `default` filter could possibly be used here, but should be discussed.

2022-08-04 12:26 UTC, pxska approved these changes
Just one more minor comment. Otherwise LGTM!

2022-08-04 12:26 UTC, pxska commented on components/settings-blog-page-layout.tpl
> +          if (data.show_older_articles_as_list === true) {
`=== true` is unnecessary.

2022-08-18 13:17 UTC, tanelj requested changes
Seems ok, but some notes.

Also:
* [x] blog `list_cols_2` and `list_cols_3` should break to 1 column layout in mobile view
* [x] It seems that "Footer" Size and Font size settings in [design editor](https://github.com/Voog/design-nuuk/blob/06b98549d8018a63ba0b19fc47a0a8dcfe57ccb5/components/template-cs-style-rules.tpl#L982) doesn't apply for user (`--layout-footer-font-size` and `--layout-footer-line-height`)

2022-08-18 13:17 UTC, tanelj commented on layouts/blog___news.tpl
> +                  {%- if forloop.index == 1 -%}
[forloop.first](https://www.voog.com/developers/markup/tags/for) can be more readable.

```suggestion
                  {%- if forloop.first -%}
```

2022-08-18 13:17 UTC, tanelj commented on sources/components/custom-styles/template-cs-header.scss
> +  #{--menu-dropdown-hover-text-color}: $white;
Seems to have been fixed

2022-08-23 13:55 UTC, pxska approved these changes

2022-08-24 06:36 UTC, tanelj approved these changes
Nice work!

2022-08-24 20:54 UTC, merged