Fix auto-gen product page breadcrumbs menu
Voog/design-nuuk pull request #92
Opened 2022-02-11 09:59 UTC by PeeterPaal

Closes #91

2022-02-14 12:44 UTC, pxska approved these changes

2022-02-16 15:33 UTC, tanelj requested changes
Works, but on regression (out of stock buy button in edit mode)

2022-02-16 15:33 UTC, tanelj commented on sources/components/custom-styles/template-cs-style-rules.scss
> +  .custom-btn:not(.custom-btn-disabled),
Autogenerated product disabled (out of stock) button text color is now wrong (black) in edit mode (ok, in preview).

edy-buy-button custom-btn custom-btn-disabled edy-buy-button-disabled
<img width="434" alt="Screenshot 2022-02-16 at 17 28 23" src="https://user-images.githubusercontent.com/378755/154298207-f44ea6cc-32ba-4178-9fa7-32117ad8a16a.png">

2022-02-17 07:17 UTC, tanelj commented on sources/components/custom-styles/template-cs-style-rules.scss
> +  .custom-btn:not(.custom-btn-disabled),
Can't reproduce any more.

2022-02-17 07:18 UTC, tanelj approved these changes

2022-02-17 08:09 UTC, pxska approved these changes

2022-02-17 11:56 UTC, merged